#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# If you want to allow non-ascii filenames set this variable to true.
allownonascii=$(git config hooks.allownonascii)

# Cross platform projects tend to avoid non-ascii filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test "$(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0')"
then
	echo "Error: Attempt to add a non-ascii file name."
	echo
	echo "This can cause problems if you want to work"
	echo "with people on other platforms."
	echo
	echo "To be portable it is advisable to rename the file ..."
	echo
	echo "If you know what you are doing you can disable this"
	echo "check using:"
	echo
	echo "  git config hooks.allownonascii true"
	echo
	exit 1
fi

if test $(git diff --cached --name-status | awk '{if ($1 != "D") print $2}'| wc -c) != 0
then
    phpFiles=$(git diff --cached --name-status | awk '{if ($1 != "D") print $2}'| grep -E '\.php' | xargs)
    for file in $phpFiles;
    do
        if test "$(/apps/php/bin/php -l $file | grep -v 'No syntax errors')"
        then
            echo "Error: There is fatal error in $file"
            exit 1
        fi
    done
    files=$(git diff --cached --name-status | awk '{if ($1 != "D") print $2}'| grep -E '\.php|\.html|\.js' | xargs)
    # delete bom
    sed -i 's/\xEF\xBB\xBF//g' $files
    # convert CRLF to LF
    sed -i 's/\r\+$//g' $files
    # replace tab to 4 spaces
    sed -i "s/\t/    /g" $files
    # delete trail space
    sed -i "s/ *$//g" $files
    # re-add the files
    git add $files
fi
exec git diff-index --check --cached $against --
